(function () {
const LEVELS = [
  { id: 'earth', en: 'Earth', ru: 'Земля', icon: 'ph-globe-hemisphere-east' },
  { id: 'solar', en: 'Solar system', ru: 'Солнечная система', icon: 'ph-sun' },
  { id: 'galaxy', en: 'Galaxy', ru: 'Галактика', icon: 'ph-spiral' },
  { id: 'universe', en: 'Universe', ru: 'Вселенная', icon: 'ph-sparkle' },
];
const BODY = { earth: '#4f8fe0', moon: '#c9c9cf', sun: '#ffb347', jupiter: '#d8a878', saturn: '#e4cf95', uranus: '#8fd6d6', neptune: '#4a6fe0' };
const EARTHS = (n) => ({ n, big: null, small: 'earth', en: 'Earths', ru: 'Земель' });
const STOPS = [
  { id: 'moscow', lv: 'earth', en: 'Moscow', ru: 'Москва', kind: 'compare', scene: true,
    fe: ['Moscow is our city. More than 13 million people live here.', 'The Kremlin walls are made of red brick and are over 500 years old.', 'The domes of St. Basil’s Cathedral look like swirly candy.'],
    fr: ['Москва — наш город. Здесь живут больше 13 миллионов человек.', 'Стены Кремля из красного кирпича. Им больше 500 лет.', 'Купола храма Василия Блаженного похожи на разноцветные конфеты.'],
    se: 'About 35 football fields would fit inside the Kremlin walls.', sr: 'Внутри стен Кремля поместилось бы около 35 футбольных полей.',
    prompt: 'Red Square in Moscow at twilight, seen from a low slightly wide angle: St. Basil’s Cathedral with swirly candy-striped onion domes in red, green, blue and gold, the red brick Kremlin wall and the Spasskaya clock tower topped with a glowing red star. Warm glowing windows, a few soft snowflakes, the first stars appearing in a deep navy sky.' },
  { id: 'russia', lv: 'earth', en: 'Russia', ru: 'Россия', kind: 'compare',
    fe: ['Russia is the biggest country on Earth.', 'Russia has 11 time zones.', 'When kids in Moscow go to bed, kids in the Far East are already waking up.'],
    fr: ['Россия — самая большая страна на Земле.', 'В России 11 часовых поясов.', 'Когда дети в Москве ложатся спать, на Дальнем Востоке дети уже просыпаются.'],
    se: 'A train from Moscow to Vladivostok takes about 7 days.', sr: 'Поезд из Москвы во Владивосток едет около 7 дней.',
    prompt: 'A cute stylized 3D globe of Earth turned to show Russia, the land gently raised like soft clay, Russia lit in warm light, a tiny glowing map pin with a heart over Moscow, a small toy-like train crossing the country, glossy blue oceans.' },
  { id: 'earth', lv: 'earth', en: 'Earth', ru: 'Земля', kind: 'compare',
    fe: ['Earth is our home. It is the only planet where we have found life.', 'Most of Earth is covered by oceans.', 'Earth spins around once a day. That’s why we have day and night.'],
    fr: ['Земля — наш дом. Это единственная планета, где мы нашли жизнь.', 'Большая часть Земли покрыта океанами.', 'Земля делает один оборот за сутки — поэтому бывают день и ночь.'],
    se: 'A plane would need about 2 days to fly all the way around Earth.', sr: 'Самолёту нужно около 2 дней, чтобы облететь всю Землю.',
    prompt: 'Planet Earth floating in space: glossy blue oceans, fluffy white swirling clouds, green and sandy continents with Europe and Russia facing the viewer, a thin glowing blue atmosphere, sunlight coming from the left.' },
  { id: 'moon', lv: 'earth', en: 'The Moon', ru: 'Луна', kind: 'count', count: { n: 50, big: 'earth', small: 'moon', en: 'Moons', ru: 'Лун' },
    fe: ['The Moon travels around Earth.', 'There is no air on the Moon, so astronauts wear space suits.', 'Astronauts’ footprints are still there. There is no wind to blow them away.'],
    fr: ['Луна летает вокруг Земли.', 'На Луне нет воздуха, поэтому космонавты ходят в скафандрах.', 'Следы астронавтов до сих пор на Луне — там нет ветра, который их сдует.'],
    se: 'About 50 Moons would fit inside Earth.', sr: 'В Землю поместилось бы около 50 Лун.',
    prompt: 'The Moon up close: soft grey surface with friendly rounded craters, a tiny astronaut in a white suit waving next to a small flag and a trail of footprints, Earth small and blue in the distance.' },
  { id: 'solarmap', lv: 'solar', en: 'Our solar system', ru: 'Солнечная система', kind: 'compare', map: true,
    fe: ['8 planets travel around the Sun. Can you find Earth?', 'Earth is the third planet from the Sun.', 'It takes Earth one whole year to go around the Sun once.'],
    fr: ['Вокруг Солнца летают 8 планет. Найдёшь Землю?', 'Земля — третья планета от Солнца.', 'Земля облетает Солнце за целый год.'],
    se: 'If the Sun were as big as a front door, Earth would be the size of a coin.', sr: 'Если Солнце — это дверь, то Земля — как монетка.' },
  { id: 'sun', lv: 'solar', en: 'The Sun', ru: 'Солнце', kind: 'count', count: { n: 1300000, big: 'sun', small: 'earth', en: 'Earths', ru: 'Земель' },
    fe: ['The Sun is a star: a giant glowing ball of hot gas.', 'It gives us light and keeps Earth warm.', 'Never look straight at the Sun. It can hurt your eyes!'],
    fr: ['Солнце — это звезда, огромный светящийся шар из горячего газа.', 'Оно дарит нам свет и согревает Землю.', 'Никогда не смотри прямо на Солнце — это вредно для глаз!'],
    se: 'More than 1 million Earths would fit inside the Sun.', sr: 'В Солнце поместилось бы больше миллиона Земель.',
    prompt: 'The Sun as a huge glowing ball of swirling orange and gold plasma with gentle looping solar flares and a warm bloom of light. No face.' },
  { id: 'mercury', lv: 'solar', en: 'Mercury', ru: 'Меркурий', kind: 'compare',
    fe: ['Mercury is the closest planet to the Sun, and the smallest.', 'A year on Mercury lasts only 88 days.', 'Days there are super hot and nights are freezing cold.'],
    fr: ['Меркурий — самая близкая к Солнцу и самая маленькая планета.', 'Год на Меркурии длится всего 88 дней.', 'Днём там очень жарко, а ночью очень холодно.'],
    se: 'Mercury is only a little bigger than our Moon.', sr: 'Меркурий лишь немного больше нашей Луны.',
    prompt: 'Mercury, a small grey-brown planet covered in craters, lit strongly from one side by an enormous bright Sun glow at the edge of the frame.' },
  { id: 'venus', lv: 'solar', en: 'Venus', ru: 'Венера', kind: 'compare',
    fe: ['Venus is the hottest planet, hotter than an oven!', 'It is wrapped in thick yellow clouds.', 'Venus spins backwards, so the Sun rises in the west.'],
    fr: ['Венера — самая горячая планета, горячее духовки!', 'Она укрыта толстыми жёлтыми облаками.', 'Венера крутится в обратную сторону, и Солнце там встаёт на западе.'],
    se: 'Venus is almost the same size as Earth, like a twin.', sr: 'Венера почти такого же размера, как Земля, — как сестра-близнец.',
    prompt: 'Venus, a planet wrapped in thick swirling pale-yellow and cream clouds with a warm hazy glow.' },
  { id: 'mars', lv: 'solar', en: 'Mars', ru: 'Марс', kind: 'compare',
    fe: ['Mars is the red planet. Its dust is like rust.', 'It has the tallest volcano we know: Olympus Mons.', 'Robot rovers drive on Mars and send us pictures.'],
    fr: ['Марс — красная планета. Его пыль похожа на ржавчину.', 'На Марсе самый высокий известный вулкан — гора Олимп.', 'По Марсу ездят роботы-марсоходы и присылают нам фотографии.'],
    se: 'Mars is about half as wide as Earth.', sr: 'Марс примерно вдвое меньше Земли в ширину.',
    prompt: 'The red planet Mars, rusty red-orange with a giant volcano and deep canyons, a tiny cute six-wheeled rover with a camera head perched on its horizon.' },
  { id: 'asteroids', lv: 'solar', en: 'Asteroid belt', ru: 'Пояс астероидов', kind: 'compare',
    fe: ['Millions of space rocks fly around the Sun between Mars and Jupiter.', 'Some are as small as pebbles, some as big as a city.'],
    fr: ['Между Марсом и Юпитером вокруг Солнца летают миллионы камней.', 'Одни маленькие, как галька, другие большие, как город.'],
    se: 'Even with millions of rocks, there is so much space between them that spaceships fly through safely.', sr: 'Даже с миллионами камней там так просторно, что космические корабли пролетают спокойно.',
    prompt: 'A field of tumbling rocky asteroids of many sizes, some pebble-small and some mountain-big, warm sunlight catching their edges, a tiny friendly spaceship weaving between them.' },
  { id: 'jupiter', lv: 'solar', en: 'Jupiter', ru: 'Юпитер', kind: 'count', count: { n: 1300, big: 'jupiter', small: 'earth', en: 'Earths', ru: 'Земель' },
    fe: ['Jupiter is the biggest planet. It is made of gas, so you can’t stand on it.', 'The Great Red Spot is a storm bigger than Earth.', 'Jupiter has more than 90 moons.'],
    fr: ['Юпитер — самая большая планета. Он из газа, на нём нельзя стоять.', 'Большое красное пятно — это буря больше, чем вся Земля.', 'У Юпитера больше 90 спутников.'],
    se: 'About 1,300 Earths would fit inside Jupiter.', sr: 'В Юпитер поместилось бы около 1300 Земель.',
    prompt: 'Jupiter, a giant planet with creamy orange, tan and white stripes and the Great Red Spot storm, with a tiny blue Earth floating beside it for size.' },
  { id: 'saturn', lv: 'solar', en: 'Saturn', ru: 'Сатурн', kind: 'count', count: { n: 760, big: 'saturn', small: 'earth', en: 'Earths', ru: 'Земель' },
    fe: ['Saturn’s rings are made of ice and rocks.', 'Saturn is so light it could float in a giant bathtub.'],
    fr: ['Кольца Сатурна сделаны из льда и камней.', 'Сатурн такой лёгкий, что поплыл бы в огромной ванне.'],
    se: 'About 760 Earths would fit inside Saturn.', sr: 'В Сатурн поместилось бы около 760 Земель.',
    prompt: 'Saturn with wide sparkling rings of ice and rock, a pale golden planet, the rings catching the light, a few ice chunks floating close to the camera.' },
  { id: 'uranus', lv: 'solar', en: 'Uranus', ru: 'Уран', kind: 'count', count: { n: 63, big: 'uranus', small: 'earth', en: 'Earths', ru: 'Земель' },
    fe: ['Uranus rolls around the Sun on its side, like a ball.', 'It is an icy, blue-green planet.'],
    fr: ['Уран катится вокруг Солнца на боку, как мячик.', 'Это ледяная голубовато-зелёная планета.'],
    se: 'About 63 Earths would fit inside Uranus.', sr: 'В Уран поместилось бы около 63 Земель.',
    prompt: 'Uranus, a smooth pale blue-green icy planet tipped over on its side, with faint thin rings running top to bottom.' },
  { id: 'neptune', lv: 'solar', en: 'Neptune', ru: 'Нептун', kind: 'count', count: { n: 57, big: 'neptune', small: 'earth', en: 'Earths', ru: 'Земель' },
    fe: ['Neptune is the farthest planet from the Sun.', 'It has the fastest winds, faster than a jet plane.', 'One year on Neptune lasts 165 Earth years.'],
    fr: ['Нептун — самая далёкая от Солнца планета.', 'Там самые сильные ветры — быстрее реактивного самолёта.', 'Один год на Нептуне длится 165 земных лет.'],
    se: 'About 57 Earths would fit inside Neptune.', sr: 'В Нептун поместилось бы около 57 Земель.',
    prompt: 'Neptune, a deep cobalt-blue planet with white streaky clouds racing across it and a dark storm spot.' },
  { id: 'pluto', lv: 'solar', en: 'Pluto', ru: 'Плутон', kind: 'compare',
    fe: ['Pluto is a dwarf planet, smaller than our Moon.', 'It has a big heart-shaped patch of ice.', 'Pluto is so far away that the Sun looks like a bright star there.'],
    fr: ['Плутон — карликовая планета, он меньше нашей Луны.', 'На нём есть большое ледяное пятно в форме сердца.', 'Плутон так далеко, что Солнце там похоже на яркую звезду.'],
    se: 'Pluto is narrower than Russia.', sr: 'Плутон меньше, чем Россия в ширину.',
    prompt: 'Pluto, a small icy dwarf planet in beige and peach tones with a big bright white heart-shaped plain, the Sun just a tiny bright star far behind it.' },
  { id: 'milkyway', lv: 'galaxy', en: 'Milky Way', ru: 'Млечный Путь', kind: 'compare',
    fe: ['Our Sun is one of billions of stars in the Milky Way galaxy.', 'It looks like a giant spinning pinwheel.', 'On a dark night outside the city you can see it as a milky stripe in the sky.'],
    fr: ['Наше Солнце — одна из миллиардов звёзд галактики Млечный Путь.', 'Она похожа на огромную крутящуюся вертушку.', 'Тёмной ночью за городом её видно как молочную полосу на небе.'],
    se: 'If you counted one star every second, it would take thousands of years.', sr: 'Если считать по одной звезде в секунду, понадобятся тысячи лет.',
    prompt: 'The Milky Way galaxy seen from above: a glowing spiral pinwheel of blue and gold stars with a bright center, and a small glowing arrow pointing to one spot in an outer arm.' },
  { id: 'andromeda', lv: 'galaxy', en: 'Andromeda', ru: 'Андромеда', kind: 'compare',
    fe: ['Andromeda is our closest big neighbor galaxy.', 'It has even more stars than the Milky Way.', 'Its light travels 2.5 million years to reach us.'],
    fr: ['Андромеда — наша ближайшая большая соседка-галактика.', 'В ней ещё больше звёзд, чем в Млечном Пути.', 'Её свет летит к нам 2,5 миллиона лет.'],
    se: 'The light we see left Andromeda before there were any people on Earth.', sr: 'Свет, который мы видим, вылетел из Андромеды, когда на Земле ещё не было людей.',
    prompt: 'The Andromeda galaxy, a huge bright tilted spiral of stars with a golden core, with the Milky Way small in a far corner.' },
  { id: 'universe', lv: 'universe', en: 'The universe', ru: 'Вселенная', kind: 'home', scene: true,
    fe: ['The universe is everything: all the galaxies, stars, planets and us.', 'There are more stars than grains of sand on all of Earth’s beaches.', 'The universe is still growing.'],
    fr: ['Вселенная — это всё: все галактики, звёзды, планеты и мы.', 'Звёзд во Вселенной больше, чем песчинок на всех пляжах Земли.', 'Вселенная до сих пор растёт.'],
    se: 'And on one small blue planet, in a city called Moscow, there’s you.', sr: 'А на маленькой голубой планете, в городе Москве, есть ты.',
    prompt: 'A deep space view full of hundreds of colorful galaxies of every shape: spirals, glowing ovals and tiny specks, like a field of jewels.' },
];
const PLANETS = [
  { id: 'mercury', a: 62, r: 6, c: '#b7a99a', p: 0.24 },
  { id: 'venus', a: 92, r: 9, c: '#e8c98a', p: 0.62 },
  { id: 'earth', a: 124, r: 10, c: '#4f8fe0', p: 1 },
  { id: 'mars', a: 156, r: 8, c: '#d9653b', p: 1.88 },
  { id: 'asteroids', a: 188, belt: true },
  { id: 'jupiter', a: 230, r: 20, c: '#d8a878', p: 11.9 },
  { id: 'saturn', a: 274, r: 16, c: '#e4cf95', p: 29.5, ring: true },
  { id: 'uranus', a: 310, r: 12, c: '#8fd6d6', p: 84 },
  { id: 'neptune', a: 340, r: 12, c: '#4a6fe0', p: 165 },
  { id: 'pluto', a: 366, r: 4, c: '#d9bfa3', p: 248 },
];
const UI = {
  en: { stop: (i, n) => `Stop ${i} of ${n}`, back: 'Back to Earth', next: 'Next', zoom: 'Zoom out', zoomTo: 'Zooming out to', showMe: 'Show me!', mapHint: 'Tap a planet to fly there!', you: 'You are here', drop: 'Drop the picture here',
    size: { compare: 'How big? How far?', count: 'How many fit?', home: 'Where are we?' } },
  ru: { stop: (i, n) => `Остановка ${i} из ${n}`, back: 'Назад на Землю', next: 'Дальше', zoom: 'Отдаляемся', zoomTo: 'Летим дальше:', showMe: 'Покажи!', mapHint: 'Нажми на планету, чтобы полететь к ней!', you: 'Мы здесь', drop: 'Перетащи сюда картинку',
    size: { compare: 'Какой размер?', count: 'Сколько поместится?', home: 'Где мы?' } },
};
const STYLE = {
  base: 'Pixar-style 3D animated film still, soft cinematic lighting with a warm rim light, rich saturated colors, smooth rounded friendly shapes, gentle glow, made for a 6-year-old.',
  iso: 'Subject centered with breathing room, on a pure black background (#000000) so it blends into a dark page.',
  scene: 'The edges of the image fade softly into pure black (#000000).',
  notext: 'No text, no letters, no numbers, no watermark.',
  wide: 'Landscape 3:2, 1536×1024.',
  square: 'Square 1:1, 1024×1024.',
};
const MASCOT = { id: 'mascot', en: 'Alosha (guide)', ru: 'Алёша',
  prompt: 'Cosmo, a small round friendly rocket character with big expressive eyes and a warm smile, white and soft lavender body, little fins used as arms, waving hello, a small puff of flame at the bottom. Full body, centered.' };
const fullPrompt = (s, square) => [s.prompt, STYLE.base, s.scene ? STYLE.scene : STYLE.iso, STYLE.notext, square ? STYLE.square : STYLE.wide].join(' ');
const IMG = {"earth":"Earth","moscow":"Moscow","russia":"Russia","moon":"Moon","sun":"Sun","mercury":"Mercury","venus":"Venus","mars":"Mars","asteroids":"asteroids","jupiter":"Jupiter","saturn":"Saturn","uranus":"Uranus","neptune":"Neptune","pluto":"Pluto","universe":"Universe"};
STOPS.forEach(s => { if (IMG[s.id]) s.img = 'uploads/Universe-images/' + IMG[s.id] + '.png'; });
STOPS[0].video = 'uploads/Universe-images/Moscow.mp4';
MASCOT.img = 'uploads/Universe-images/Cosmo.png';
window.UNIVERSE = { LEVELS, STOPS, PLANETS, BODY, UI, STYLE, MASCOT, fullPrompt };
})();
